### ISSUE TITLE
where to download the pretrained model?

### ISSUE THREAD

**Issue by pumpkin007** [braindeadpool/bf-vos#2]
@braindeadpool excellent work for reproducing the model!

May I know where to download the pretrained model:
deeplabv2_resnet_pretrained_compatible2.pth

**Comment by braindeadpool** [comment]
Hi @pumpkin007,
Here's the pre-trained model: https://drive.google.com/open?id=1jwT70zQsNtSMDEgCH2r1lPXYT3O8prIp

**Comment by braindeadpool** [comment]
Closing issue.
